/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface AnnotationsComponent {
      'annotationsUrl': string;
      'author': string;
      'org': string;
      'portalUrl': string;
      'search': string;
      'target': string;
    }
  }

  interface HTMLAnnotationsComponentElement extends StencilComponents.AnnotationsComponent, HTMLStencilElement {}

  var HTMLAnnotationsComponentElement: {
    prototype: HTMLAnnotationsComponentElement;
    new (): HTMLAnnotationsComponentElement;
  };
  interface HTMLElementTagNameMap {
    'annotations-component': HTMLAnnotationsComponentElement;
  }
  interface ElementTagNameMap {
    'annotations-component': HTMLAnnotationsComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'annotations-component': JSXElements.AnnotationsComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface AnnotationsComponentAttributes extends HTMLAttributes {
      'annotationsUrl'?: string;
      'author'?: string;
      'org'?: string;
      'portalUrl'?: string;
      'search'?: string;
      'target'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;